namespace: project-b

commonLabels:
  owner: team-a
  app: project-b

commonAnnotations:
  configmanagement.gke.io/cluster-selector: selector-environment-prod

resources:
- ../base

patches:
- target:
    kind: RoleBinding
    name: developer-role
  patch: |-
    - op: replace
      path: /subjects/0/name
      value: project-b-developers@company.com
- target:
    kind: Namespace
    name: default-name
  patch: |-
    - op: replace
      path: /metadata/name
      value: project-b
