apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    configmanagement.gke.io/cluster-selector: selector-environment-dev
  name: developer-edit
  namespace: default-name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: Group
  name: project-a-developers@company.com
  apiGroup: rbac.authorization.k8s.io
