namespace: project-a

commonLabels:
  owner: team-a
  app: project-a

resources:
- ../base
- developer-conditional-edit.yaml

patches:
- target:
    kind: RoleBinding
    name: developer-role
  patch: |-
    - op: replace
      path: /subjects/0/name
      value: project-a-developers@company.com
- target:
    kind: Namespace
    name: default-name
  patch: |-
    - op: replace
      path: /metadata/name
      value: project-a
